name: Nightly Build

on:
  push:
    branches: [main]

jobs:
  determine-deployment:
    name: Determine Deployment Destination
    runs-on: ubuntu-latest
    outputs:
      ecr_repository: ${{ steps.set-repo.outputs.ecr_repository }}
      tag: ${{ steps.get-latest-tag.outputs.tag }}
      ec2_host: ${{ steps.get-latest-tag.outputs.ec2_host }}
    
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          repository: ccrawford4/devops-midterm-source
          fetch-tags: true
      
      - name: Get Latest Tag
        id: get-latest-tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.get-latest-tag.outputs.tag }}
          regex: '```v\.\d\.\d{2}-rc\d```'
      
      - name: Echo Tag
        run: echo "${{ steps.get-latest-tag.outputs.tag}}"

      - name: Determine ECR Repository
        id: set-repo
        run: |
          if [[ "${{ steps.regex-match.outputs.match }}" == "true" ]]; then
            echo "Using RC ECR Repository"
            echo "ecr_repository=${{ secrets.RC_ECR_REPOSITORY_URI }}" >> $GITHUB_OUTPUT
            echo "ec2_host=${{ secrets.RC_EC2_HOST }}" >> $GITHUB_OUTPUT
          else
            echo "Using QA ECR Repository"
            echo "ecr_repository=${{ secrets.QA_ECR_REPOSITORY_URI }}" >> $GITHUB_OUTPUT
            echo "ec2_host=${{ secrets.QA_EC2_HOST }}" >> $GITHUB_OUTPUT
          fi

  smoke_test:
    name: Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 paramiko requests
  
      - name: Launch EC2 instance and run tests
        id: ec2-deploy
        run: |
          python smoke_test.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          EC2_SSH_KEY: ${{ secrets.EC2_PEM }}
          LAUNCH_TEMPLATE_ID: ${{ secrets.LAUNCH_TEMPLATE_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EC2_USER: ${{ secrets.EC2_USER }}
          HEALTH_CHECK_URL: ${{ secrets.HEALTH_CHECK_URL }}
          SOURCE_REPO: ${{ secrets.SOURCE_REPO }}

  push-to-ecr:
    needs: [smoke_test, determine-deployment]
    name: Build Docker Images and Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          repository: ccrawford4/devops-midterm-source
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Echo Test
        run: echo "${{ needs.determine-deployment.outputs.ecr_repository }}"

      - name: Echo Test 2
        run: echo "${{ needs.determine-deployment.outputs.ec2_host }}"
      
      - name: "Echo Test 3"
        run: echo "${{ needs.determine-deployment.outputs.ecr_repository }}"

      - name: Build, tag, and push Docker images
        env:
          ECR_REPOSITORY: ${{ needs.determine-deployment.outputs.ecr_repository }}
          TAG: ${{ needs.determine-deployment.outputs.tag }}
        run: |
          for service in frontend backend; do
            cd $service
            docker build -t $service .

            docker tag $service $ECR_REPOSITORY:$service-$TAG
            docker tag $service $ECR_REPOSITORY:$service-latest

            docker push $ECR_REPOSITORY:$service-$TAG
            docker push $ECR_REPOSITORY:$service-latest
            cd ..
          done
    
  deploy:
    needs: [push-to-ecr, determine-deployment]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v4

      - name: Run Deploy Script
        run: |
          chmod +x ./run.sh
          ./run.sh "${{ secrets.EC2_PEM }}" \
                  "${{ secrets.EC2_USER }}" \
                  "${{ needs.determine-deployment.outputs.ec2_host }}" \
                  "${{ secrets.AWS_ACCESS_KEY_ID }}" \
                  "${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
                  "${{ secrets.AWS_SESSION_TOKEN }}" \
                  "${{ secrets.AWS_REGION }}" \
                  "${{ needs.determine-deployment.outputs.ecr_repository }}" \
                  "${{ secrets.DB_DSN }}"